repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/PyCQA/isort
  rev: 5.8.0
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: 21.4b0
  hooks:
    - id: black
      args: [--safe, --quiet, --line-length=120]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      types: [python]
      args: ["--ignore-missing-imports", "--scripts-are-modules"]
      require_serial: true
      additional_dependencies: []
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
            "-rn",
            "-sn",
            "--rcfile=pylintrc"
            ]
